### ISSUE TITLE
Server fails to start

### ISSUE THREAD

**Issue by lstone** [12foo/event-flyer-factory#7]
system: mac osx 10.10.5, python 3.4
description: after running pip to install dependencies, server fails with error "AttributeError: class Layout has no attribute '__subclasses__'"

![2015-09-11 08 27 35 am](https://cloud.githubusercontent.com/assets/972730/9818746/f7f02766-585e-11e5-90cf-95b12d3e59cc.png)

**Comment by 12foo** [comment]
Hi! Are you certain you're using Python 3.4 to start the server? On some systems it gets installed as `python3` and `python` keeps pointing to Python 2.

**Comment by 12foo** [comment]
I just put in some code that should make it work under 2.7 as well, but I don't guarantee that it'll keep working. :) Please reopen if you continue to have problems.
